# Generated by Django 2.1.4 on 2018-12-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0002_auto_20150904_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['display_name']},
        ),
        migrations.AlterField(
            model_name='backend',
            name='klass',
            field=models.CharField(help_text='Example: notifier.backends.EmailBackend', max_length=500),
        ),
    ]
